class Employee :
    print("I AM A PARENT CLASS OR A BASE CLASS")

class Prog (Employee) :
    print("I AM CHILD CLASS DERIVED FROM THE PARENT OR THE BASE CLASS I WILL INHERIT EVERYTHING FROM PARENT CLASS")

h=Prog()

# THIS IS THE EXAMPLE OF SINGLE INHERITANCE