class Employee :
    print("I AM A PARENT CLASS OR A BASE CLASS")

class Prog () :
    print("I AM CHILD CLASS DERIVED FROM THE PARENT OR THE BASE CLASS I WILL INHERIT EVERYTHING FROM PARENT CLASS")

class coder(Employee,Prog) :
    print("I AM THE CHILD CLASS MIX OF 2 PARENTS CLASS")

h=coder()
